### ISSUE TITLE
Pendientes

### ISSUE THREAD

**Issue by LuisScoccola** [manuelF/isw2#1]
- Agregar timer al tomador de decisiones
- Conectar tomador de decisiones al historial (tiene que loguear decisiones y leer el ultimo sensado)
- Definir las tres entradas posibles del historial
- Conectar Condiciones Externas al historial (tiene que loguear condiciones) 
- Eliminar conexio entre condiciones externas y decisiones
- Serializar Master Plan e Historial de y a archivos
- Conectar clase arduino

**Comment by LucianoGandini** [comment]
Hecho: Agregar timer al tomador de decisiones
